// OG Image proxy - serves pre-generated JPG images from R2 via API
// Images are generated by scripts/generate-og-images.ts and uploaded to R2

const API_BASE = 'https://nft-api.simplethings.workers.dev';

export const onRequest: PagesFunction = async (context) => {
  // Extract token ID from filename (e.g., "123.jpg" -> "123")
  const file = context.params.id as string;
  const tokenId = file.replace('.jpg', '');

  // Validate token ID
  if (!/^\d+$/.test(tokenId)) {
    return new Response('Invalid token ID', { status: 400 });
  }

  // Fetch JPG from API (which reads from R2)
  const response = await fetch(`${API_BASE}/api/og/${tokenId}`);

  if (!response.ok) {
    return new Response('OG image not found', { status: 404 });
  }

  // Return with aggressive caching
  return new Response(response.body, {
    headers: {
      'Content-Type': 'image/jpeg',
      'Cache-Control': 'public, max-age=31536000, immutable',
    },
  });
};
